### ISSUE TITLE
Runtime error occurs on every run

### ISSUE THREAD

**Issue by Rindrics** [Rindrics/execute-scripts-github-flow#29]
---

{"time":"2024-04-01T20:23:18.476733933Z","level":"INFO","msg":"starting application"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4ecc5[8](https://github.com/Rindrics/poop/actions/runs/8513262932/job/23316622400#step:4:9)]

goroutine 1 [running]:
log/slog.(*Logger).Handler(...)
	/usr/local/go/src/log/slog/logger.go:122
log/slog.(*Logger).Enabled(0xc0000[9](https://github.com/Rindrics/poop/actions/runs/8513262932/job/23316622400#step:4:10)8090?, {0x6264c8?, 0x7b2ac0?}, 0x1?)
	/usr/local/go/src/log/slog/logger.go:169 +0x18
log/slog.(*Logger).log(0x0, {0x6264c8, 0x7b2ac0}, 0xfffffffffffffffc, {0x5d2[12](https://github.com/Rindrics/poop/actions/runs/8513262932/job/23316622400#step:4:13)f, 0x19}, {0xc0000e7c08, 0x2, 0x2})
	/usr/local/go/src/log/slog/logger.go:242 +0x6a
log/slog.(*Logger).Debug(...)
	/usr/local/go/src/log/slog/logger.go:200
github.com/Rindrics/execute-script-with-merge/infrastructure.EventParser.ParseEvent({0x753200?})
	/dist/infrastructure/parser.go:51 +0xc5
github.com/Rindrics/execute-script-with-merge/application.(*App).ParseEvent(0xc0000945a0)
	/dist/application/types.go:38 +0xd2
main.main()
	/dist/main.go:22 +0x27f

**Comment by Rindrics** [comment]
resolved by #37
